from typing import Union, ClassVar, Self

# Types that can be converted into our C types
_Numeric = Union[int, float, "CNumBase"] # in operators
_Constructable = Union[_Numeric, bytes] # in constructors (allows constructing from bytes as well)

# Binary operations return either a CNum or a standard Python float
_Return = Union["CNumBase", float]

class CNumBase:
    @property
    def value(self) -> Union[int, float]: ...

    def to_bytes(self) -> bytes: ...
    
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __bool__(self) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    
    # Arithmetic (returns promoted result)
    def __add__(self, other: _Numeric) -> _Return: ...
    def __radd__(self, other: _Numeric) -> _Return: ...
    def __sub__(self, other: _Numeric) -> _Return: ...
    def __rsub__(self, other: _Numeric) -> _Return: ...
    def __mul__(self, other: _Numeric) -> _Return: ...
    def __rmul__(self, other: _Numeric) -> _Return: ...
    def __truediv__(self, other: _Numeric) -> _Return: ...
    def __rtruediv__(self, other: _Numeric) -> _Return: ...

    # In-place (returns same type as self, truncated as in C)
    def __iadd__(self, other: _Numeric) -> Self: ...
    def __isub__(self, other: _Numeric) -> Self: ...
    def __imul__(self, other: _Numeric) -> Self: ...
    def __itruediv__(self, other: _Numeric) -> Self: ...
    
    # Unary
    def __neg__(self) -> Self: ...
    def __abs__(self) -> Self: ...

    # Comparison
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: _Numeric) -> bool: ...
    def __le__(self, other: _Numeric) -> bool: ...
    def __gt__(self, other: _Numeric) -> bool: ...
    def __ge__(self, other: _Numeric) -> bool: ...

class CIntBase(CNumBase):
    @property
    def value(self) -> int: ...  # Overridden to always be int
    
    def __floordiv__(self, other: _Numeric) -> _Return: ...
    def __rfloordiv__(self, other: _Numeric) -> _Return: ...
    def __ifloordiv__(self, other: _Numeric) -> Self: ...
    
    def __mod__(self, other: _Numeric) -> _Return: ...
    def __rmod__(self, other: _Numeric) -> _Return: ...
    def __imod__(self, other: _Numeric) -> Self: ...
    
    def __and__(self, other: _Numeric) -> _Return: ...
    def __rand__(self, other: _Numeric) -> _Return: ...
    def __iand__(self, other: _Numeric) -> Self: ...
    
    def __or__(self, other: _Numeric) -> _Return: ...
    def __ror__(self, other: _Numeric) -> _Return: ...
    def __ior__(self, other: _Numeric) -> Self: ...
    
    def __xor__(self, other: _Numeric) -> _Return: ...
    def __rxor__(self, other: _Numeric) -> _Return: ...
    def __ixor__(self, other: _Numeric) -> Self: ...
    
    def __lshift__(self, other: _Numeric) -> _Return: ...
    def __rlshift__(self, other: _Numeric) -> _Return: ...
    def __ilshift__(self, other: _Numeric) -> Self: ...
    
    def __rshift__(self, other: _Numeric) -> _Return: ...
    def __rrshift__(self, other: _Numeric) -> _Return: ...
    def __irshift__(self, other: _Numeric) -> Self: ...
    
    def __invert__(self) -> Self: ...
    def __index__(self) -> int: ...

class CFloatBase(CNumBase):
    @property
    def value(self) -> float: ... # Overridden to always be float

# Individual Number Classes
class Int8(CIntBase):
    size: ClassVar[int] = 1
    is_signed: ClassVar[bool] = True
    def __init__(self, value: _Constructable) -> None: ...
    @staticmethod
    def from_bytes(data: bytes) -> "Int8": ...

class UInt8(CIntBase):
    size: ClassVar[int] = 1
    is_signed: ClassVar[bool] = False
    def __init__(self, value: _Constructable) -> None: ...
    @staticmethod
    def from_bytes(data: bytes) -> "UInt8": ...

class Int16(CIntBase):
    size: ClassVar[int] = 2
    is_signed: ClassVar[bool] = True
    def __init__(self, value: _Constructable) -> None: ...
    @staticmethod
    def from_bytes(data: bytes) -> "Int16": ...

class UInt16(CIntBase):
    size: ClassVar[int] = 2
    is_signed: ClassVar[bool] = False
    def __init__(self, value: _Constructable) -> None: ...
    @staticmethod
    def from_bytes(data: bytes) -> "UInt16": ...

class Int32(CIntBase):
    size: ClassVar[int] = 4
    is_signed: ClassVar[bool] = True
    def __init__(self, value: _Constructable) -> None: ...
    @staticmethod
    def from_bytes(data: bytes) -> "Int32": ...

class UInt32(CIntBase):
    size: ClassVar[int] = 4
    is_signed: ClassVar[bool] = False
    def __init__(self, value: _Constructable) -> None: ...
    @staticmethod
    def from_bytes(data: bytes) -> "UInt32": ...

class Int64(CIntBase):
    size: ClassVar[int] = 8
    is_signed: ClassVar[bool] = True
    def __init__(self, value: _Constructable) -> None: ...
    @staticmethod
    def from_bytes(data: bytes) -> "Int64": ...

class UInt64(CIntBase):
    size: ClassVar[int] = 8
    is_signed: ClassVar[bool] = False
    def __init__(self, value: _Constructable) -> None: ...
    @staticmethod
    def from_bytes(data: bytes) -> "UInt64": ...

class Float32(CFloatBase):
    size: ClassVar[int] = 4
    is_signed: ClassVar[bool] = True
    def __init__(self, value: _Constructable) -> None: ...
    @staticmethod
    def from_bytes(data: bytes) -> "Float32": ...

class Float64(CFloatBase):
    size: ClassVar[int] = 8
    is_signed: ClassVar[bool] = True
    def __init__(self, value: _Constructable) -> None: ...
    @staticmethod
    def from_bytes(data: bytes) -> "Float64": ...

class Float80(CFloatBase):
    size: ClassVar[int] = 10
    is_signed: ClassVar[bool] = True
    def __init__(self, value: _Constructable) -> None: ...
    @staticmethod
    def from_bytes(data: bytes) -> "Float80": ...

# Aliases
Char = Int8
UChar = UInt8
Short = Int16
UShort = UInt16
Int = Int32
UInt = UInt32
Long = Int64
ULong = UInt64
Float = Float32
Double = Float64
LongDouble = Float80