from typing import Optional

from pyx64dbg.number_types import UInt64


def traceme() -> None: ...
def cont(pid: int, signal: Optional[int] = None) -> None: ...
def get_standard_regs(pid: int) -> dict[str, bytes]: ...
def get_extended_regs(pid: int) -> dict[str, bytes]: ...
def set_standard_regs(pid: int, regs: dict[str, bytes]) -> None: ...
def set_extended_regs(pid: int, regs: dict[str, bytes]) -> None: ...
def single_step(pid: int, signal: Optional[int]=None) -> None: ...
def get_memory_range(pid: int, start_address: int, length: int) -> bytes: ...
def write_memory_range(pid: int, start_address: int, data: bytes) -> None: ...
def kill(pid: int) -> None: ...