def traceme() -> None: ...
def cont(pid: int) -> None: ...
def peekdata(pid: int, address: int) -> int: ...
def pokedata(pid: int, address: int, data: int) -> None: ...
def getregs(pid: int) -> dict: ... # TODO update
def setregs(pid: int, regs: dict) -> None: ... # TODO update
def single_step(pid: int) -> None: ...