def traceme() -> None: ...
def cont(pid: int, signal=None) -> None: ...
def peekdata(pid: int, address: int) -> int: ...
def pokedata(pid: int, address: int, data: int) -> None: ...
def get_standard_regs(pid: int) -> dict: ...
def get_extended_regs(pid: int) -> dict: ...
def get_debug_regs(pid: int) -> dict: ...
def set_standard_regs(pid: int, regs: dict) -> None: ...
def set_extended_regs(pid: int, regs: dict) -> None: ...
def set_debug_regs(pid: int, regs: dict) -> None: ...
def single_step(pid: int, signal=None) -> None: ...
def get_memory_range(pid: int, start_address: int, length: int) -> bytes: ...
def write_memory_range(pid: int, start_address: int, data: bytes) -> None: ...
def kill(pid: int) -> None: ...